/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'InteriorNotFound': RouteRecordInfo<'InteriorNotFound', '/:InteriorNotFound(.*)', { InteriorNotFound: ParamValue<true> }, { InteriorNotFound: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/assembly/ButtonTest': RouteRecordInfo<'/assembly/ButtonTest', '/assembly/ButtonTest', Record<never, never>, Record<never, never>>,
    '/assembly/DemoView': RouteRecordInfo<'/assembly/DemoView', '/assembly/DemoView', Record<never, never>, Record<never, never>>,
    '/assembly/NetTest': RouteRecordInfo<'/assembly/NetTest', '/assembly/NetTest', Record<never, never>, Record<never, never>>,
    '/assembly/SignView': RouteRecordInfo<'/assembly/SignView', '/assembly/SignView', Record<never, never>, Record<never, never>>,
    '/assembly/TableTest': RouteRecordInfo<'/assembly/TableTest', '/assembly/TableTest', Record<never, never>, Record<never, never>>,
    '/homePage': RouteRecordInfo<'/homePage', '/homePage', Record<never, never>, Record<never, never>>,
    '/jurisdiction/admin': RouteRecordInfo<'/jurisdiction/admin', '/jurisdiction/admin', Record<never, never>, Record<never, never>>,
    '/jurisdiction/editor': RouteRecordInfo<'/jurisdiction/editor', '/jurisdiction/editor', Record<never, never>, Record<never, never>>,
    '/jurisdiction/visitor': RouteRecordInfo<'/jurisdiction/visitor', '/jurisdiction/visitor', Record<never, never>, Record<never, never>>,
    '/login-[redirect]': RouteRecordInfo<'/login-[redirect]', '/login-:redirect', { redirect: ParamValue<true> }, { redirect: ParamValue<false> }>,
    '/one/one': RouteRecordInfo<'/one/one', '/one/one', Record<never, never>, Record<never, never>>,
    '/one/two/three/three': RouteRecordInfo<'/one/two/three/three', '/one/two/three/three', Record<never, never>, Record<never, never>>,
    '/one/two/two': RouteRecordInfo<'/one/two/two', '/one/two/two', Record<never, never>, Record<never, never>>,
    'https://17359898647.github.io/': RouteRecordInfo<'https://17359898647.github.io/', '/outsideChain/LineNet', Record<never, never>, Record<never, never>>,
    '/outsideChain/NaiveUi': RouteRecordInfo<'/outsideChain/NaiveUi', '/outsideChain/NaiveUi', Record<never, never>, Record<never, never>>,
    '/outsideChain/VueJs': RouteRecordInfo<'/outsideChain/VueJs', '/outsideChain/VueJs', Record<never, never>, Record<never, never>>,
    '/outsideChain/VueUse': RouteRecordInfo<'/outsideChain/VueUse', '/outsideChain/VueUse', Record<never, never>, Record<never, never>>,
    '/setting/MenuSetting': RouteRecordInfo<'/setting/MenuSetting', '/setting/MenuSetting', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
