/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./../layout/BackTop.vue')['default']
    BreadCrumbs: typeof import('./../layout/BreadCrumbs/BreadCrumbs.vue')['default']
    Collaps: typeof import('./../layout/BreadCrumbs/Collaps.vue')['default']
    ContentView: typeof import('./../layout/ContentView.vue')['default']
    CountTo: typeof import('./../components/CountTo/CountTo.vue')['default']
    Dark: typeof import('./../layout/BreadCrumbs/Dark.vue')['default']
    FooterView: typeof import('./../layout/FooterView.vue')['default']
    FullScreen: typeof import('./../layout/BreadCrumbs/fullScreen.vue')['default']
    HeaderView: typeof import('./../layout/HeaderView.vue')['default']
    HKeepAlive: typeof import('./../layout/HKeepAlive/HKeepAlive.vue')['default']
    IframeCom: typeof import('./../components/IframeCom/IframeCom.vue')['default']
    IframeKeep: typeof import('./../layout/HKeepAlive/IframeKeep.vue')['default']
    Layout: typeof import('./../layout/index.vue')['default']
    MenuView: typeof import('./../layout/MenuView.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    Refresh: typeof import('./../layout/BreadCrumbs/Refresh.vue')['default']
    RippleButton: typeof import('./../components/RippleButton/RippleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderView: typeof import('./../layout/SiderView.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/SvgIcon.vue')['default']
    TagsView: typeof import('./../layout/TagView/TagsView.vue')['default']
    ThemeView: typeof import('./../layout/ThemeView/ThemeView.vue')['default']
  }
}
