/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./../layout/BackTop.vue')['default']
    BreadCrumbs: typeof import('./../layout/BreadCrumbs/BreadCrumbs.vue')['default']
    Collaps: typeof import('./../layout/BreadCrumbs/Collaps.vue')['default']
    ContentView: typeof import('./../layout/ContentView.vue')['default']
    CountTo: typeof import('./../components/CountTo/CountTo.vue')['default']
    Dark: typeof import('./../layout/BreadCrumbs/Dark.vue')['default']
    FooterView: typeof import('./../layout/FooterView.vue')['default']
    FullScreen: typeof import('./../layout/BreadCrumbs/fullScreen.vue')['default']
    HeaderView: typeof import('./../layout/HeaderView.vue')['default']
    HKeepAlive: typeof import('./../layout/HKeepAlive/HKeepAlive.vue')['default']
    IframeCom: typeof import('./../components/IframeCom/IframeCom.vue')['default']
    IframeKeep: typeof import('./../layout/HKeepAlive/IframeKeep.vue')['default']
    Layout: typeof import('./../layout/index.vue')['default']
    MenuView: typeof import('./../layout/MenuView.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH5: typeof import('naive-ui')['NH5']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    Refresh: typeof import('./../layout/BreadCrumbs/Refresh.vue')['default']
    RippleButton: typeof import('./../components/RippleButton/RippleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderView: typeof import('./../layout/SiderView.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/SvgIcon.vue')['default']
    TagsView: typeof import('./../layout/TagView/TagsView.vue')['default']
    ThemeView: typeof import('./../layout/ThemeView/ThemeView.vue')['default']
  }
}
