<template>
  <NCard title="普通按钮">
    <NSpace>
      <RippleButton
        :secondary="true"
        strong
      >
        Default
      </RippleButton>
      <RippleButton
        :secondary="true"
        strong
        type="tertiary"
      >
        Tertiary
      </RippleButton>
      <RippleButton
        :secondary="true"
        strong
        type="primary"
      >
        Primary
      </RippleButton>
      <RippleButton
        :secondary="true"
        strong
        type="info"
      >
        Info
      </RippleButton>
      <RippleButton
        :secondary="true"
        strong
        type="success"
      >
        Success
      </RippleButton>
      <RippleButton
        :secondary="true"
        strong
        type="warning"
      >
        Warning
      </RippleButton>
      <RippleButton
        :secondary="true"
        strong
        type="error"
      >
        Error
      </RippleButton>
      <RippleButton

        round
        :secondary="true"
        strong
      >
        Default
      </RippleButton>
      <RippleButton
        round
        :secondary="true"
        strong
        type="primary"
      >
        Primary
      </RippleButton>
      <RippleButton
        round
        :secondary="true"
        strong
        type="info"
      >
        Info
      </RippleButton>
      <RippleButton
        round
        :secondary="true"
        strong
        type="success"
      >
        Success
      </RippleButton>
      <RippleButton
        round
        :secondary="true"
        strong
        type="warning"
      >
        Warning
      </RippleButton>
      <RippleButton
        round
        :secondary="true"
        strong
        type="error"
      >
        Error
      </RippleButton>
      <RippleButton
        circle
        secondary
        strong
      >
        <template #icon>
          <SvgIcon lineIcon="mdi:square-inc-cash" />
        </template>
      </RippleButton>
      <RippleButton
        circle
        secondary
        strong
        type="primary"
      >
        <template #icon>
          <SvgIcon lineIcon="mdi:square-inc-cash" />
        </template>
      </RippleButton>
      <RippleButton
        circle
        secondary
        strong
        type="info"
      >
        <template #icon>
          <SvgIcon lineIcon="mdi:square-inc-cash" />
        </template>
      </RippleButton>
      <RippleButton
        circle
        secondary
        strong
        type="success"
      >
        <template #icon>
          <SvgIcon lineIcon="mdi:square-inc-cash" />
        </template>
      </RippleButton>
      <RippleButton
        circle
        secondary
        strong
        type="warning"
      >
        <template #icon>
          <SvgIcon lineIcon="mdi:square-inc-cash" />
        </template>
      </RippleButton>
      <RippleButton
        circle
        secondary
        strong
        type="error"
      >
        <template #icon>
          <SvgIcon lineIcon="mdi:square-inc-cash" />
        </template>
      </RippleButton>
    </NSpace>
  </NCard>
</template>
