name: CI Github Pages
on:
  # 监听push操作
  push:
    branches:
      - master # 这里只配置了main分支，所以只有推送main分支才会触发以下任务
  workflow_dispatch:
  merge_group: {}
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install and Build
        run: |
          bun install
          bun run build
      - name: Deploy # 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # 部署后提交到那个分支
          folder: dist # 这里填打包好的目录名称
          token: ${{ secrets.DEPLOY }}
          repository-name: 17359898647/17359898647.github.io # 你的github pages仓库地址
